version: '3.1'

services:

  spacedlearnDB:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: spacedlearn
    ports:
      - 27017:27017
    volumes:
      - ./mongo/entrypoint:/docker-entrypoint-initdb.d