version: '3.1'
services:
  spaced_learn_db:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: mathias/spaced_learn_db
    container_name: spaced_learn_db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/entrypoint/:/docker-entrypoint-initdb.d/